"""add audio_path to scenes

Revision ID: 1c4c707ddebb
Revises: adc6988c317c
Create Date: 2026-06-03 13:38:29.736469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c4c707ddebb'
down_revision: Union[str, Sequence[str], None] = 'adc6988c317c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenes', sa.Column('audio_path', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenes', 'audio_path')
    # ### end Alembic commands ###
