"""add creative direction columns to scenes

Revision ID: 227545b6d05a
Revises: 992820b2e5c3
Create Date: 2026-06-04 18:00:02.235477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '227545b6d05a'
down_revision: Union[str, Sequence[str], None] = '992820b2e5c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenes', sa.Column('storyboard', sa.Text(), nullable=True))
    op.add_column('scenes', sa.Column('camera_movement', sa.String(length=50), nullable=True))
    op.add_column('scenes', sa.Column('camera_intensity', sa.String(length=20), nullable=True))
    op.add_column('scenes', sa.Column('framing', sa.String(length=50), nullable=True))
    op.add_column('scenes', sa.Column('expression_slug', sa.String(length=50), nullable=True))
    op.add_column('scenes', sa.Column('pose_slug', sa.String(length=50), nullable=True))
    op.add_column('scenes', sa.Column('gaze_direction', sa.String(length=30), nullable=True))
    op.add_column('scenes', sa.Column('emotion', sa.String(length=50), nullable=True))
    op.add_column('scenes', sa.Column('image_prompt', sa.Text(), nullable=True))
    op.add_column('scenes', sa.Column('animation_prompt', sa.Text(), nullable=True))
    op.add_column('scenes', sa.Column('cut_plan', sa.JSON(), nullable=True))
    op.add_column('scenes', sa.Column('narration_cues', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenes', 'narration_cues')
    op.drop_column('scenes', 'cut_plan')
    op.drop_column('scenes', 'animation_prompt')
    op.drop_column('scenes', 'image_prompt')
    op.drop_column('scenes', 'emotion')
    op.drop_column('scenes', 'gaze_direction')
    op.drop_column('scenes', 'pose_slug')
    op.drop_column('scenes', 'expression_slug')
    op.drop_column('scenes', 'framing')
    op.drop_column('scenes', 'camera_intensity')
    op.drop_column('scenes', 'camera_movement')
    op.drop_column('scenes', 'storyboard')
    # ### end Alembic commands ###
