"""create video_jobs table

Revision ID: a18e2f522c73
Revises: 
Create Date: 2026-06-01 21:00:52.932949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a18e2f522c73'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('topic', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RESEARCHING', 'EDITORIAL', 'SCRIPTING', 'FACT_CHECKING', 'NARRATING', 'VISUALS', 'EDITING', 'SUBTITLING', 'READY_FOR_REVIEW', 'PUBLISHING', 'DONE', 'FAILED', name='job_status'), nullable=False),
    sa.Column('error', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_jobs_status'), 'video_jobs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_jobs_status'), table_name='video_jobs')
    op.drop_table('video_jobs')
    # ### end Alembic commands ###
