"""add fact-check columns to scenes

Revision ID: adc6988c317c
Revises: b3b6400a33de
Create Date: 2026-06-02 23:21:32.022129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adc6988c317c'
down_revision: Union[str, Sequence[str], None] = 'b3b6400a33de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenes', sa.Column('needs_review', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('scenes', sa.Column('review_reason', sa.String(length=500), nullable=True))
    op.add_column('scenes', sa.Column('supporting_fact_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_scenes_supporting_fact_id'), 'scenes', ['supporting_fact_id'], unique=False)
    op.create_foreign_key(None, 'scenes', 'facts', ['supporting_fact_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scenes', type_='foreignkey')
    op.drop_index(op.f('ix_scenes_supporting_fact_id'), table_name='scenes')
    op.drop_column('scenes', 'supporting_fact_id')
    op.drop_column('scenes', 'review_reason')
    op.drop_column('scenes', 'needs_review')
    # ### end Alembic commands ###
