"""create sources and facts tables

Revision ID: cfba5b2cb7dc
Revises: d795a6500347
Create Date: 2026-06-02 16:12:41.592871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfba5b2cb7dc'
down_revision: Union[str, Sequence[str], None] = 'd795a6500347'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sources', sa.Column('reliability', sa.Integer(), nullable=False))
    op.add_column('sources', sa.Column('published_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sources', 'published_at')
    op.drop_column('sources', 'reliability')
    # ### end Alembic commands ###
