"""create editorial_angles table

Revision ID: fd0c0ba428aa
Revises: cfba5b2cb7dc
Create Date: 2026-06-02 17:21:24.060792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd0c0ba428aa'
down_revision: Union[str, Sequence[str], None] = 'cfba5b2cb7dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('editorial_angles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('persona', sa.String(length=500), nullable=False),
    sa.Column('thesis', sa.Text(), nullable=False),
    sa.Column('hook', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['video_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_editorial_angles_job_id'), 'editorial_angles', ['job_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_editorial_angles_job_id'), table_name='editorial_angles')
    op.drop_table('editorial_angles')
    # ### end Alembic commands ###
